### ISSUE TITLE
Add a way of disabling overwriting `WP_CACHE` value in wp-config.php

### ISSUE THREAD

**Issue by jenkoian** [kovshenin/page-caching#17]
Upon install, whatever the value of `WP_CACHE` is in `wp-config.php` is [removed](https://github.com/kovshenin/surge/blob/main/include/install.php#L47-L52) it would be good to be able to disable this behaviour, useful for cases where config is configured from env vars and plugins are installed as part of a build process for example. 

I'm happy to provide a PR, but just wanted to run it by you first. Would you be happy with wrapping in a conditional with a filter?

**Comment by kovshenin** [comment]
Sure! Could you provide an example of a config file where you wouldn't want to replace the constant? I'm guessing it's just set to whatever is in getenv()?

**Comment by jenkoian** [comment]
Yeah exactly: https://github.com/boxuk/wp-project-skeleton/blob/main/wp-config.php#L114

**Comment by kovshenin** [comment]
Cool, yeah a PR would be appreciated!
