### ISSUE TITLE
Manipulating PHP globals

### ISSUE THREAD

**Issue by nlemoine** [kovshenin/page-caching#25]
Hi! 

While playing around with Surge, I noticed the plugin makes changes to PHP globals at various places:
- https://github.com/kovshenin/surge/blob/e68d4be79ab7fafe54799413962d9ea9a9150768/include/common.php#L143
- https://github.com/kovshenin/surge/blob/e68d4be79ab7fafe54799413962d9ea9a9150768/include/common.php#L115-L118
- https://github.com/kovshenin/surge/blob/e68d4be79ab7fafe54799413962d9ea9a9150768/include/common.php#L107-L108

Is it intended?

Since `key()` is called [on every request](https://github.com/kovshenin/surge/blob/e68d4be79ab7fafe54799413962d9ea9a9150768/include/serve.php#L20), you may end up messing with third party code that relies on those globals and not only on edge cases.

**Comment by kovshenin** [comment]
This is intended yes, the reason we remove cookies from the list is to avoid unintended consequences, where a cookie is set to be ignored from cache, but actually used elsewhere in PHP. Same with other request-related globals.
