### ISSUE TITLE
PHP warnings

### ISSUE THREAD

**Issue by timiwahalahti** [kovshenin/page-caching#26]
PHP version 7.4.30
Surge version 1.0.4

This combination results in the following PHP warnings

`PHP Warning:  Use of undefined constant DIR - assumed 'DIR' (this will throw an Error in a future version of PHP) in /var/www/doma.in/config/application.php on line 70`

`PHP Warning:  include(DIR/cache-config.php): failed to open stream: No such file or directory in /var/www/doma.in/content/plugins/surge/include/common.php on line 56`

We are using bedrock based structure, hence the content/plugins.

**Comment by haydenjames** [comment]
It seems the plugin is dead. Sad. It's such a unicorn in a field of bloated plugins when all you need is a basic cache.

**Comment by kovshenin** [comment]
The error is caused by the config file, not the Surge plugin. Looks like you're using an undefined DIR for the `WP_CACHE_CONFIG` constant. Please re-open if that's not the case, happy to investigate further.
