### ISSUE TITLE
It seems Health in WP does not see the caching header

### ISSUE THREAD

**Issue by uhlhosting** [kovshenin/page-caching#31]
No client caching response headers were detected.

**Comment by MadtownLems** [comment]
I do not get that same Site Health warning in any of our networks. Have you confirmed that it IS actually working properly, by checking the response headers.  Look for the X-Cache header in the response. You should see a value of 'hit' if it's working properly.

**Comment by uhlhosting** [comment]
@MadtownLems Yes the cache result is hit. Yet nothing in health still.
